services:
  - type: web
    name: image-forensics-app
    env: python
    buildCommand: ""
    startCommand: gunicorn main:app --bind 0.0.0.0:8000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: CELERY_BROKER_URL
        value: redis://image-forensics-redis:6379/0
      - key: CELERY_RESULT_BACKEND
        value: redis://image-forensics-redis:6379/0

  - type: worker
    name: image-forensics-worker
    env: python
    buildCommand: ""
    startCommand: celery -A celery_worker.celery worker --loglevel=info
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: CELERY_BROKER_URL
        value: redis://image-forensics-redis:6379/0
      - key: CELERY_RESULT_BACKEND
        value: redis://image-forensics-redis:6379/0

  - type: redis
    name: image-forensics-redis
    ipAllowList: []  # accessible to all services in this render.yaml